# Generated by Django 5.2.9 on 2026-03-10 10:18

import django.db.models.deletion
import wagtailmarkdown.fields

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.WAGTAILDOCS_DOCUMENT_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentConversion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("converted_content", wagtailmarkdown.fields.MarkdownField(blank=True, null=True)),
                ("allow_indexing", models.BooleanField(default=False)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_conversion",
                        to=settings.WAGTAILDOCS_DOCUMENT_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Conversion",
                "verbose_name_plural": "Document Conversions",
            },
        ),
    ]
