# Generated by Django 5.2.9 on 2026-01-02 13:54

import django.db.models.deletion
import taggit.managers
import wagtail.models.media
import wagtail.search.index
import wagtailmarkdown.fields

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        ("wagtailcore", "0094_alter_page_locale"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("file", models.FileField(upload_to="documents", verbose_name="file")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("file_size", models.PositiveBigIntegerField(editable=False, null=True)),
                ("file_hash", models.CharField(blank=True, editable=False, max_length=40)),
                (
                    "conversion_exempt",
                    models.BooleanField(
                        default=False,
                        help_text="Check this box to skip automatic conversion to accessible HTML format",
                        verbose_name="Exempt from accessible version",
                    ),
                ),
                (
                    "conversion_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("exempt", "Exempt"),
                            ("not_applicable", "N/A"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Conversion Status",
                    ),
                ),
                (
                    "converted_content",
                    wagtailmarkdown.fields.MarkdownField(
                        blank=True,
                        help_text="Markdown content generated from PDF conversion",
                        null=True,
                        verbose_name="Converted Content (Markdown)",
                    ),
                ),
                (
                    "converted_content_allow_indexing",
                    models.BooleanField(
                        default=False,
                        help_text="Check this box to allow search engines to index the content",
                        verbose_name="Converted content search engines indexing",
                    ),
                ),
                ("conversion_metrics", models.JSONField(blank=True, default=dict)),
                (
                    "is_pdf",
                    models.BooleanField(
                        default=False, editable=False, help_text="Automatically determined based on file type on save."
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        default=wagtail.models.media.get_root_collection_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.collection",
                        verbose_name="collection",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True, help_text=None, through="taggit.TaggedItem", to="taggit.Tag", verbose_name="tags"
                    ),
                ),
                (
                    "uploaded_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
