# Generated by Django 5.2.9 on 2026-03-10 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customdocument",
            name="converted_content",
        ),
        migrations.RemoveField(
            model_name="customdocument",
            name="converted_content_allow_indexing",
        ),
    ]
